spring:
  kafka:
    consumer:
      group-id: tpd-loggers
      auto-offset-reset: earliest
    # change this property if you are using your own
    # Kafka cluster or your Docker IP is different
    bootstrap-servers: localhost:9092

queue:
  kafka:
    entry-queue-name: kafka-entry-queue
    final-queue-name: kafka-final-queue